from ubuntu
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Shanghai
RUN sed -i 's/archive.ubuntu.com/mirrors.ustc.edu.cn/g' /etc/apt/sources.list
RUN apt update
RUN apt install -y zip
RUN apt install -y  mingw-w64-tools mingw-w64-common g++-mingw-w64 gcc-mingw-w64 upx-ucl osslsigncode unzip python3
WORKDIR /darkarmour
COPY darkarmour-master_2.zip .
RUN unzip -P 123456 darkarmour-master_2.zip
RUN unzip darkarmour-master.zip
WORKDIR /darkarmour/darkarmour-master